### ISSUE TITLE
layer-shell surfaces

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [Smithay/client-toolkit#115]
It would be nice to add some initial support for layer-shell surfaces.
For example, these can be used by apps who need to display a top-level 'overlay' window.
While that's often the default initial configuration with stacking WM, this extra semantic precision helps tiling WM.
https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-layer-shell-unstable-v1.xml
Looks like it could be a variant of ShellSurface.
That would make it easy to use by Window and maybe eventually winit.

**Comment by vberger** [comment]
For now, SCTK mostly lacks helpers for layer-shell because it didn't appear to be completely clear what kind of useful helpers could be provided. Yet, layer-shell is completely supported (see the [`layer_shell` example](https://github.com/Smithay/client-toolkit/blob/master/examples/layer_shell.rs)), it's just that SCTK does not provide helpers beyond wayland-protocols.

> Looks like it could be a variant of ShellSurface.

The semantics of a layer surface are quite different from the ones of a shell surface, and many properties of one don't really make sense for the other. Thus it does not seem very appropriate to integrate them into `ShellSurface`, which is rather meant to abstract over the various versions of the shell protocols, which all have quite similar semantics.

However an other helper for layer surfaces would definitely have a place in SCTK, if it can meaningfully add something on top of the wayland-protocols API.

> For example, these can be used by apps who need to display a top-level 'overlay' window.

I'm not completely clear regarding what you mean by that to be quite honest.

**Comment by Matthias-Fauconneau** [comment]
My goal is to assign an iced app to the 'overlay' layer.
I think the easiest would be to have winit keep using an sctk::Window which assign layer-shell instead of xdg-shell.
In the layer-shell case, the exposed unsupported shell operations can be safely ignored since an app using layer-shell should not need them.
But this way it can also fallback transparently to xdg-shell when layer-shell cannot be used.

**Comment by kchibisov** [comment]
Just of curiosity

Why do you need `winit` if you're using `layer-shell`, like it will be a Wayland only app, in the end? I'm not sure that other OSes/X11 has something like that at all.

**Comment by Matthias-Fauconneau** [comment]
I do not need the cross-platform capabilities of winit, but that's what
iced use.
Forking iced winit backend into a wayland backend doesn't seem like the
best solution.

**Comment by kchibisov** [comment]
>I do not need the cross-platform capabilities of winit, but that's what
iced use.

winit is about  bringing cross platform abstractions for devs to work with, just using layer-shell in some cases isn't for upstream winit IMHO, since layer-shell is too specific (anchors, groups, etc). And knowing that layer-shell is used for something primitive(bars, etc), just cairo + pango should be already enough to solve most problems. I wonder if iced could just have a group of public traits which apps could implement and use their windowing library instead of winit, that should solve your problem for sure. From what I see you can likely patch iced to do so ( it already has a lot of related code to that if not a proper support).
