### ISSUE TITLE
Rounded decoration corners

### ISSUE THREAD

**Issue by JMS55** [Smithay/client-toolkit#151]
Like how GTK rounds the top left and right window corners.

**Comment by kchibisov** [comment]
The problem is that this thing is very subjective and controlling the amount of roundness is something that sounds like something not desirable to expose for users. Especially knowing that we can't round all the corners.

If something should be added to decorations is shadows, since the window doesn't have a visible border, so it could match the window behind.

**Comment by JMS55** [comment]
Do you think it would be something that belongs in winit then?

Shadows would actually be very nice, I didn't realize there weren't any, but now that I do it feels very off without shadows.

**Comment by kchibisov** [comment]
I strongly believe that rounded corners should be done by compositor, so they'll look consistent at least, winit can't do anything anything about rounded corners, since it's not the one who draws, so the client should do rounded corners themself, however it doesn't have access to decoration frame. So adding rounded corners is a mess, unless it's done in compositor, where it's way nicer, since you draw the entire window in the end.

if the goal is to have rounded corners for your client side decorations you may create your own `Frame` with rounded corners.
