### ISSUE TITLE
Scope of client-toolkit

### ISSUE THREAD

**Issue by dvc94ch** [Smithay/client-toolkit#44]
What is the scope of client-toolkit? It seems to me that some of the stuff that is handled in winit could be moved over here, like utilities for hidpi handling for example.

I could just use winit of course but I'm interested in experimenting with a new wayland protocol for creating menus, like for example in macosx where they are part of the window manager. In particular I want to create a spacemacs style compositor.

**Comment by vberger** [comment]
I'd be favorable to merging any feature that is general enough to be useful to a large set of users of SCTK, as long as it also follows the general principes from [CONTRIBUTING.md](https://github.com/Smithay/client-toolkit/blob/master/CONTRIBUTING.md#scope--structure).

So it's entirely possible that stuff that is currently done in winit could be moved into SCTK. If it hasn't been yet, it's probably because I haven't figured out a way to express it in a general enough way. If you have any ideas regarding that, please don't hesitate to share them! I'd suggest creating different issues for different features, in order to keep things easy to follow.
