### ISSUE TITLE
Remove dependency on rand()?

### ISSUE THREAD

**Issue by fschutt** [Smithay/client-toolkit#50]
https://github.com/Smithay/client-toolkit/blob/b19ab63131c918812464a3eb67e5c71465e28bb4/src/utils/mempool.rs#L250

As far as I can see, this is the only use of the `rand` crate in this entire library. The problem is that winit (the main user of this crate) also depends on rand(), but a different, incompatible version (`0.6.1` vs sctk: `0.5.*`). This means, if I compile winit, I have two duplicated versions of the rand crate.

But does opening file descriptors have to be cryptographically secure? Otherwise, I'd replace this with a simple xorshift or something different, since as far as I can see it's only about "opening the next available file descriptor".

Otherwise, would it be possible to update the rand dependency and publish it to crates, so that winit and sctk use the same major version of rand?

**Comment by dvc94ch** [comment]
> Otherwise, would it be possible to update the rand dependency and publish it to crates, so that winit and sctk use the same major version of rand?

Yeah, that's a good idea anyway since the dpi pr for winit is still open...

**Comment by vberger** [comment]
I released version 0.4.3 updating the dependencies. I'll leave this open because I'm not completely decided about what to do in the long run.

I'm in favor of using as few dependencies as possible in general (notably to avoid this kind of issues), though I'm not sure I'd want to maintain a random number generator in SCTK..

**Comment by fschutt** [comment]
Well, for very simple RNG generators, I've always used a simple xorshift:

```rust
static RAND_SEED: AtomicUsize = AtomicUsize::new(2100);

/// Simple rand() function (32-bit)
fn rand_xorshift() -> usize {
    let mut x = RAND_SEED.fetch_add(21, Ordering::SeqCst);
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    x
}
```

Also, since wayland runs only on Linux, you could always just open /dev/random and get some random numbers that way.

**Comment by trimental** [comment]
The creation of the shared memory file using shm_open() doesn't really require a full random number generator. You just need one fairly random number to start with but the numbers that come after that could just be increments of the original number.

Something like the nano subseconds of a duration since a point in time would work almost equally as in https://github.com/Smithay/client-toolkit/pull/61.
